### ISSUE TITLE
Progress?

### ISSUE THREAD

**Issue by SupremeTechnopriest** [runspired/shared-worker-polyfill-experiment#1]
Hows it going?  Just wondering if you made any progress with this experiment.  I'm shaking my fist at the webkit team, hoping that safari falls off a bridge and drowns sooner than later.  If you have any insight you can share before I start down the same rabbit hole, it would be greatly appreciated!

**Comment by runspired** [comment]
@SupremeTechnopriest happy to talk through things I tried (localStorage / SW / postMessage). Roughly speaking if you have SW you can largely polyfill shared workers across tabs, but at a min it's fairly easy to implement shared workers within a single tab.

**Comment by SupremeTechnopriest** [comment]
Yeah ended up just using a service worker.  Turned out alright!
